events {}

http {
  # -------------------------
  # Load Balancing: Frontend
  # -------------------------
  # upstream frontend {
  #   server web1:5173;
  #   server web2:5173;
  # }

  # -------------------------
  # Load Balancing: Backend
  # -------------------------
  upstream backend {
    server server1:3000;
    server server2:3000;
  }

  # -------------------------
  # Load Balancing: Auth Service
  # -------------------------

  upstream authService {
    server auth1:3000;
  }

  # -------------------------
  # Main Server
  # -------------------------
  server {
    listen 4890;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # -------------------------
    # Frontend (React / Vite)
    # -------------------------
    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;

      # We changed from 2 instance of frontend to one + i changed the client side to work on the build script (dist)
      # proxy_pass http://frontend;

      # proxy_http_version 1.1; #Vite is annoying with NGINX so it needs these settings
      # proxy_set_header Host $host;
      # proxy_set_header Upgrade $http_upgrade;
      # proxy_set_header Connection "upgrade";
    }

    # -------------------------
    # Backend API
    # -------------------------
    location /api/ {
      rewrite ^/api/(.*)$ /$1 break; #remove /api from the backend request (because we don't use /api on our routes in the backend)
      proxy_pass http://backend;
    }

    location /authentication/ {
      rewrite ^/authentication/(.*)$ /$1 break;
      proxy_pass http://authService;
    }
  }
}