events {}

http {
  # -------------------------
  # Load Balancing: Frontend
  # -------------------------
  upstream frontend {
    server web1:5173;
    server web2:5173;
  }

  # -------------------------
  # Load Balancing: Backend
  # -------------------------
  upstream backend {
    server server1:3000;
    server server2:3000;
  }

  # -------------------------
  # Main Server
  # -------------------------
  server {
    listen 4890;

    # -------------------------
    # Frontend (React / Vite)
    # -------------------------
    location / {
      proxy_pass http://frontend;

      proxy_http_version 1.1; #Vite is annoying with NGINX so it needs these settings
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # -------------------------
    # Backend API
    # -------------------------
    location /api/ {
      rewrite ^/api/(.*)$ /$1 break; #remove /api from the backend request (because we don't use /api on our routes in the backend)
      proxy_pass http://backend;

      
    }
  }
}